#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycvapi-deployment
spec:
  selector:
    matchLabels:
      app: mycvapi-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mycvapi-server
    spec:
      containers:
      - name: mycvapi-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/jorgeaveraf/mycv-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mycvapi-service
  name: mycvapi-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: mycvapi-server
  type: LoadBalancer